# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
